"""Add an index to the full_name column

Revision ID: 07a4e4ee31e6
Revises: 9cb0aa74e470
Create Date: 2024-10-18 17:14:20.956105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a4e4ee31e6'
down_revision: Union[str, None] = '9cb0aa74e470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_full_name', 'employees', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_full_name', table_name='employees')
    # ### end Alembic commands ###
